### ISSUE TITLE
Example link is broken in README

### ISSUE THREAD

**Issue by itsfaizankhan** [victrme/homemade-wysiwyg#4]
The Example link in README seems to be pointing to Netlify while the working link is [pocketeditor.victr.me](https://pocketeditor.victr.me/)

**Comment by itsfaizankhan** [comment]
Created a [PR](https://github.com/victrme/pocket-editor/pull/5) for you 👍

**Comment by victrme** [comment]
Thanks 👍
Netlify is out, Cloudflare Pages is in !
