### ISSUE TITLE
Compliance with web componence

### ISSUE THREAD

**Issue by alan-khosro** [victrme/homemade-wysiwyg#7]
I could not use your editor with web components (shadow root). The reason: your constructor accept string selector.
Solution: let we pass element instead (or both):
```
constructor (selector: string | HTMLElement, options: Options)
```

Would you also publish it on JSR (you have opened it but not done yet).

**Comment by victrme** [comment]
Thanks for the heads up @alan-khosro!

I'll publish it on JSR soon enough. I'm trying to keep the repo compatible with npmjs while having a perfect score on JSR... This will take some time 🤔
